[build]
  publish = "dist/"
  command = "gulp build"

[template.environment]
  MY_ACCOUNT_ID = "Account ID for tracking code"
  MY_SITE_NAME = "Site name"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval' *.app-us1.com trackcmp.net;"
